In [25]:
'''
numpy is the short from of numerical python.
in 2006 Travis Oliphant created NumPy package.
NumPy is a package that defines a multi-dimensional objects and associates fast math functions that operate on NumPy.
I talso has functions for working in domain of linear Algebra, Fourier Transformation and Matrices.
In simple words it a fundamental package for Numerical analysis.  
'''
import numpy as np

In [26]:
arr1= np.array([10,30,67,78,562,68])  # numpy arrays uses less memory space and reading of elements / data is faster.
arr2=np.array([20,45,4,78,89,6])
print(arr*arr2)

[  200  1350   268  6084 50018   408]


In [27]:
'''
ARRAY v/s LIST
- A list cannot directly handle Mathematical Operations while Array can.
- An Array consumes less memory space than list.
- Using of array is faster than list.
- A List can store different dataTypes, while array cannot do that.
- A list can easily modified bcoz elemsnts are stored individually.It is easy to Add and Delete elements.
- In list One can have nested data with different size, while you cannot do the same in array.
'''
numpyArray = np.array([23,56,87,34])
list_python = [34,'67',56,90.7,'char']
print(list_python, numpyArray)


[34, '67', 56, 90.7, 'char'] [23 56 87 34]


In [28]:
twoD = np.array([[20,30,4,67],[201,56,74,78]])
twoD

array([[ 20,  30,   4,  67],
       [201,  56,  74,  78]])

In [38]:
# method for concatenate
a=np.array([[23,45,6],[73,5,6]])
b=np.array([[1,2,3],[4,5,6]])
np.concatenate([a,b])

# enclose the arrays in the parenthasis as shown, if not you will get an error.
'''
[[23, 45,  6],
[73,  5,  6],
[ 1,  2,  3],
[ 4,  5,  6]]
'''

'\n[[23, 45,  6],\n[73,  5,  6],\n[ 1,  2,  3],\n[ 4,  5,  6]]\n'

In [39]:
np.concatenate([a,b], axis=1) # axis attribute chooses the alignment of array structure
'''
[[23, 45,  6,  1,  2,  3],
[73,  5,  6,  4,  5,  6]]
'''

'\n[[23, 45,  6,  1,  2,  3],\n[73,  5,  6,  4,  5,  6]]\n'

In [40]:
np.hstack([a,b])  # hstcak defines Horizontal stack


array([[23, 45,  6,  1,  2,  3],
       [73,  5,  6,  4,  5,  6]])

In [41]:
np.vstack([a,b])  # vstack defines vertical stack

array([[23, 45,  6],
       [73,  5,  6],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [47]:
# splitting of ARRAYS
t1= np.array([1,2,3,4,5,6,7,8,9])
t2=np.array_split(t1,3)
t2  # [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [55]:
'''
Updating Inserting Deleting of elements in ARRAYS
np.append(h,g) 
np.insert(a,1,5) 
np.delete(a,[2])
'''
a= np.array([[20,40,30,50]])
print(np.append(a,[90,100])) # [ 20  40  30  50  90 100]
print(np.insert(a,2,120))    # [20  40 120  30  50]
print(np.delete(a,3))        #[20 40 30]

[ 20  40  30  50  90 100]
[ 20  40 120  30  50]
[20 40 30]


In [65]:
 '''
 Sorting, Searching and Filtering of Arrays
 
 '''
s=np.array([9,56,3,436,87,6344,76,880])
print(np.sort(s)) #([   3,    9,   56,   76,   87,  436,  880, 6344])
print(np.where(s==6344)[0]) #[5]
print(np.where(s==6344)) #(array([5], dtype=int64),)
print(np.searchsorted(s,880))  # takes 2 arguments and returns the index of the given argument in the array
fa= s>100
new=s[fa]  # filter the values greaterthan 100
print(new) #[ 436 6344  880]


[   3    9   56   76   87  436  880 6344]
[5]
(array([5], dtype=int64),)
7
[ 436 6344  880]


In [79]:
'''
AGGREGATE FUNCTIONS
'''
print(np.sum(s))  #7891
print(np.average(s)) #986.375
print(np.max(s)) #6344
print(np.min(s)) #3
print(np.mean(s)) #986.375
print(np.median(s)) #81.5
print(np.size(s)) #8
print(np.cumsum(s)) #[   9   65   68  504  591 6935 7011 7891] - cumulative sum
print(np.cumprod(s)) #[        9         504        1512      659232    57353184 -1223620864 1494094848   543473664] - cumulative product

7891
986.375
6344
3
986.375
81.5
8
[   9   65   68  504  591 6935 7011 7891]
[          9         504        1512      659232    57353184 -1223620864
  1494094848   543473664]


In [78]:
x= np.array([[2,3,45,6,43,667,8],[21,24,56,78,653,56,78]])
print(np.cumsum(x)) # [   2    5   50   56   99  766  774  795  819  875  953 1606 1662 1740] - cumulative sum of 2D array

[   2    5   50   56   99  766  774  795  819  875  953 1606 1662 1740]
